#!/usr/bin/env python3
"""Encode an existing wallpaper for flash-backed LVGL use. Requires Pillow.

This build-time conversion has no runtime image decoder or full-frame allocation.
The generated C file is checked in, so regular firmware builds need no Pillow.
"""
from pathlib import Path
from PIL import Image, ImageOps
root = Path(__file__).resolve().parents[1]
source = root / 'firmware/clock/assets/blue-hour-source.png'
out = root / 'firmware/clock/main/home_wallpaper.c'
image = ImageOps.fit(Image.open(source).convert('RGB'), (480, 320), method=Image.Resampling.LANCZOS)
values = [((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3) for r, g, b in image.getdata()]
with out.open('w') as f:
    f.write('/* Generated by scripts/encode-clock-wallpaper.py; pixels remain in flash. */\n#include "lvgl.h"\nstatic const uint16_t pixels[] = {\n')
    for i in range(0, len(values), 16):
        f.write(','.join(f'0x{x:04x}' for x in values[i:i+16]) + ',\n')
    f.write('};\nconst lv_image_dsc_t home_wallpaper = {\n.header = {.magic=LV_IMAGE_HEADER_MAGIC, .cf=LV_COLOR_FORMAT_RGB565, .w=480, .h=320, .stride=960},\n.data_size=sizeof(pixels), .data=(const uint8_t *)pixels\n};\n')
