#!/usr/bin/env python3
"""Generate future POSIX rules from installed IANA TZif footers. No historical rules."""
from pathlib import Path
import json
root = Path('/usr/share/zoneinfo')
version = (root / 'tzdata.zi').read_text().splitlines()[0]
rows = []
for path in sorted(root.rglob('*')):
    name = str(path.relative_to(root))
    if not path.is_file() or name.startswith(('posix/', 'right/')):
        continue
    data = path.read_bytes()
    if not data.startswith((b'TZif2', b'TZif3', b'TZif4')):
        continue
    rule = data.split(b'\n')[-2].decode('ascii') if data.endswith(b'\n') else ''
    if rule:
        rows.append((name, rule))
output = Path(__file__).resolve().parents[1] / 'firmware/clock/main/timezone_rules.c'
output.write_text('// Generated by scripts/generate-timezones.py; ' + version + '\n'
    '#include "timezone_rules.h"\n#include <string.h>\n'
    'static const struct {const char *name,*rule;} zones[]={\n' +
    ''.join('    {' + json.dumps(n) + ',' + json.dumps(r) + '},\n' for n,r in rows) +
    '};\nconst char *timezone_rule(const char *name)\n{\n'
    '    if(!name)return 0;\n'
    '    for(unsigned i=0;i<sizeof(zones)/sizeof(zones[0]);i++)if(!strcmp(name,zones[i].name))return zones[i].rule;\n'
    '    return 0;\n}\n')
print(f'Generated {len(rows)} rules from {version}')
